package com.gu.mediaservice.lib.cleanup

import com.gu.mediaservice.model.ImageMetadata

object PhotographerRenamer extends MetadataCleaner {
  val names = Map(
    "Adam Warzawa" -> "Adam Warżawa",
    "Akos Stiller" -> "Ákos Stiller",
    "Alberto E Rodriguez" -> "Alberto E Rodríguez",
    "Alecsandra Raluca Dragoi" -> "Alecsandra Raluca Drăgoi",
    "Alejandro Garcia" -> "Alejandro García",
    "Aleksander Kozminski" -> "Aleksander Koźmiński",
    "Alex Caparros" -> "Álex Caparrós",
    "Ali Ihsan Ozturk" -> "Ali İhsan Öztürk",
    "Alik Keplicz" -> "Alik Kęplicz",
    "Alvaro Barrientos" -> "Álvaro Barrientos",
    "Alvin Baez" -> "Alvin Báez",
    "Andre Penner" -> "André Penner",
    "Andreea Campeanu" -> "Andreea Câmpeanu",
    "Andrej Isakovic" -> "Andrej Isaković",
    "Andres Kudacki" -> "Andrés Kudacki",
    "Angel Martinez" -> "Ángel Martínez",
    "Antonio Bronic" -> "Antonio Bronić",
    "Antonio Lacerda" -> "António Lacerda",
    "Arif Hudaverdi Yaman" -> "Arif Hüdaverdi Yaman",
    "Attila Kovacs" -> "Attila Kovács",
    "Aurelien Meunier" -> "Aurélien Meunier",
    "Azael Rodriguez" -> "Azael Rodríguez",
    "Balazs Mohai" -> "Balázs Mohai",
    "Bartlomiej Zborowski" -> "Bartłomiej Zborowski",
    "Benoit Jacques" -> "Benoît Jacques",
    "Berk Ozkan" -> "Berk Özkan",
    "Bernadett Szabo" -> "Bernadett Szabó",
    "Bernat Armangue" -> "Bernat Armangué",
    "Bilgin S Sasmaz" -> "Bilgin S Şaşmaz",
    "Bjorn Larsson Rosvall" -> "Björn Larsson Rosvall",
    "Boris Kovacev" -> "Boris Kovačev",
    "Brendan Mcdermid" -> "Brendan McDermid",
    "Bulent Kilic" -> "Bülent Kılıç",
    "Burak Cingi" -> "Burak Çıngı",
    "Carlos Alvarez" -> "Carlos Álvarez",
    "Carlos Barria" -> "Carlos Barría",
    "Carlos Garcia Rawlins" -> "Carlos García Rawlins",
    "Cathal Mcnaughton" -> "Cathal McNaughton",
    "Cem Oksuz" -> "Cem Öksüz",
    "Cesar Manso" -> "César Manso",
    "Christophe Petit Tesson" -> "Christophe Petit-Tesson",
    "Cj Gunther" -> "CJ Gunther",
    "Cristobal Herrera" -> "Cristóbal Herrera",
    "Cristobal Venegas" -> "Cristóbal Venegas",
    "Czarek Sokolowski" -> "Czarek Sokołowski",
    "Dado Ruvic" -> "Dado Ruvić",
    "Damir Sagolj" -> "Damir Šagolj",
    "Daniel Garcia" -> "Daniel García",
    "Daniel Mihailescu" -> "Daniel Mihăilescu",
    "Daniel Muñoz" -> "Daniel Muñoz",
    "Darko Bandic" -> "Darko Bandić",
    "Darko Vojinovic" -> "Darko Vojinović",
    "Dave M Benett" -> "David M Benett",
    "David Mcnew" -> "David McNew",
    "David W Cerny" -> "David W Černý",
    "David Wolff - Patrick" -> "David Wolff-Patrick",
    "Dawid Zuchowicz" -> "Dawid Żuchowicz",
    "Diana Sanchez" -> "Diana Sánchez",
    "Don Mcphee" -> "Don McPhee",
    "Eduardo Munoz" -> "Eduardo Muñoz",
    "Eduardo Munoz Alvarez" -> "Eduardo Muñoz",
    "Elif Ozturk" -> "Elif Öztürk",
    "Erdem Sahin" -> "Erdem Şahin",
    "Eric Piermont" -> "Éric Piermont",
    "Esteban Felix" -> "Esteban Félix",
    "Eugene Garcia" -> "Eugene García",
    "Francois Duhamel" -> "François Duhamel",
    "Francois Durand" -> "François Durand",
    "Francois Guillot" -> "François Guillot",
    "Francois Lenoir" -> "François Lenoir",
    "Francois Mori" -> "François Mori",
    "Francois Nel" -> "François Nel",
    "Francois-Xavier Marit" -> "François-Xavier Marit",
    "Gerard Julien" -> "Gérard Julien",
    "Gergely Janossy" -> "Gergely Jánossy",
    "Goran Kovacic" -> "Goran Kovačić",
    "Goran Tomasevic" -> "Goran Tomašević",
    "Grzegorz Michalowski" -> "Grzegorz Michałowski",
    "Hannah Mckay" -> "Hannah McKay",
    "Hector Retamal" -> "Héctor Retamal",
    "Helene Pambrun" -> "Hélène Pambrun",
    "Herika Martinez" -> "Hérika Martínez",
    "Ian Macnicol" -> "Ian MacNicol",
    "Inti Ocon" -> "Inti Ocón",
    "Ints Kalnins" -> "Ints Kalniņš",
    "Isa Terli" -> "İsa Terli",
    "Jakub Kaminski" -> "Jakub Kamiński",
    "Javier Garcia" -> "Javier García",
    "Javier Lizon" -> "Javier Lizón",
    "Jean-Francois Badias" -> "Jean-François Badias",
    "Jean-Francois Monier" -> "Jean-François Monier",
    "Jean-Paul Pelissier" -> "Jean-Paul Pélissier",
    "Jean-Sebastien Evrard" -> "Jean-Sébastien Evrard",
    "Jerome Delay" -> "Jérôme Delay",
    "Jerome Favre" -> "Jérôme Favre",
    "Jesus Diges" -> "Jesús Diges",
    "Johan Ordonez" -> "Johan Ordóñez",
    "John Macdougall" -> "John MacDougall",
    "John Vizcaino" -> "John Vizcaíno",
    "Jon Gustafsson" -> "Jón Gústafsson",
    "Jorg Carstensen" -> "Jörg Carstensen",
    "Jose Cabezas" -> "José Cabezas",
    "Jose Cendon" -> "José Cendón",
    "Jose Fragozo" -> "José Fragozo",
    "Jose Giribas" -> "José Giribás",
    "Jose Jordan" -> "José Jordan",
    "Jose Luis Gonzalez" -> "José Luis González",
    "Jose Luis Magana" -> "José Luis Magaña",
    "Jose Luis Saavedra" -> "José Luis Saavedra",
    "Jose Palazon" -> "José Palazón",
    "Jose Sena Goulao" -> "José Sena Goulão",
    "Juan Naharro Gimenez" -> "Juan Naharro Giménez",
    "Kai Schwoerer" -> "Kai Schwörer",
    "Kamil Krzaczynski" -> "Kamil Krzaczyński",
    "Laszlo Balogh" -> "László Balogh",
    "Laurence Mathieu-Leger" -> "Laurence Mathieu-Léger",
    "Laurent Gillieron" -> "Laurent Gilliéron",
    "Lech Muszynski" -> "Lech Muszyński",
    "Leo Correa" -> "Léo Corrêa",
    "Leonhard Foeger" -> "Leonhard Föger",
    "Lise Aserud" -> "Lise Åserud",
    "Lluis Gene" -> "Lluís Gené",
    "Loic Venance" -> "Loïc Venance",
    "Lucio Tavora" -> "Lúcio Távora",
    "Lukasz Cynalewski" -> "Łukasz Cynalewski",
    "Lukasz Szelemej" -> "Łukasz Szełemej",
    "Maciej Kulczynski" -> "Maciej Kulczyński",
    "Maciek Jazwiecki" -> "Maciek Jaźwiecki",
    "Mahmut Serdar Alakus" -> "Mahmut Serdar Alakuş",
    "Manu Fernandez" -> "Manu Fernández",
    "Marcelo Del Pozo" -> "Marcelo del Pozo",
    "Marcio Jose Sanchez" -> "Marcio José Sánchez",
    "Mario Arturo Martinez" -> "Mario Arturo Martínez",
    "Mario Vazquez" -> "Mario Vázquez",
    "Marko Djurica" -> "Marko Đurica",
    "Marko Drobnjakovic" -> "Marko Drobnjaković",
    "Martin Mejia" -> "Martín Mejía",
    "Matthias Schrader" -> "Matthias Schräder",
    "Mauricio Duenas Castaneda" -> "Mauricio Dueñas Castañeda",
    "Michal Cízek" -> "Michal Čížek",
    "Michelle Mcloughlin" -> "Michelle McLoughlin",
    "Miguel Gutierrez" -> "Miguel Gutiérrez",
    "Milos Bicanski" -> "Miloš Bičanski",
    "Moises Castillo" -> "Moisés Castillo",
    "Morne de Klerk" -> "Morné de Klerk",
    "Mustafa Ciftci" -> "Mustafa Çiftçi",
    "Niklas Halle’N" -> "Niklas Halle’n",
    "Oscar del Pozo" -> "Óscar del Pozo",
    "Osman Orsal" -> "Osman Örsal",
    "Ozan Kose" -> "Ozan Köse",
    "Ozge Elif Kizil" -> "Özge Elif Kızıl",
    "Ozkan Bilgin" -> "Özkan Bilgin",
    "Pablo Blazquez Dominguez" -> "Pablo Blázquez Domínguez",
    "Pablo Martinez Monsivais" -> "Pablo Martínez Monsiváis",
    "Pal Hansen" -> "Pål Hansen",
    "Patricia de Melo Moreira" -> "Patrícia de Melo Moreira",
    "Paul Mcerlane" -> "Paul McErlane",
    "Pawel Jaszczuk" -> "Paweł Jaszczuk",
    "Pawel Kopczynski" -> "Paweł Kopczyński",
    "Peter Dejong" -> "Peter de Jong",
    "Rade Prelic" -> "Rade Prelić",
    "Rafal Guz" -> "Rafał Guz",
    "Ramon Espinosa" -> "Ramón Espinosa",
    "Raul Arboleda" -> "Raúl Arboleda",
    "Raul Caro Cadenas" -> "Raúl Caro Cadenas",
    "Reinnier Kaze" -> "Reinnier Kazé",
    "Remi Chauvin" -> "Rémi Chauvin",
    "Remus Tiplea" -> "Remus Țiplea",
    "Remy Gabalda" -> "Rémy Gabalda",
    "Ricardo Mazalan" -> "Ricardo Mazalán",
    "Rolex Dela Pena" -> "Rolex dela Peña",
    "Romain Jacquet-Lagreze" -> "Romain Jacquet-Lagrèze",
    "Sanjin Strukic" -> "Sanjin Strukić",
    "Sebastian Tataru" -> "Sebastian Tătaru",
    "Sebastiao Moreira" -> "Sebastião Moreira",
    "Sebastiao Salgado " -> "Sebastião Salgado ",
    "Sebastien Bozon" -> "Sébastien Bozon",
    "Sebastien Nogier" -> "Sébastien Nogier",
    "Sebastien Salom Gomis" -> "Sébastien Salom-Gomis",
    "Sebastien Thibault" -> "Sébastien Thibault",
    "Sergio Morae" -> "Sérgio Morae",
    "Sergio Perez" -> "Sergio Pérez Sanz",
    "Sergio Perez" -> "Sergio Pérez",
    "Srdjan Stevanovic" -> "Srđan Stevanović",
    "Srdjan Suki" -> "Srđan Suki",
    "Stanislaw Rozpedzik" -> "Stanisław Rozpędzik",
    "Stephane de Sakutin" -> "Stéphane de Sakutin",
    "Stephane Mahe" -> "Stéphane Mahé",
    "Stephanie Lecocq" -> "Stéphanie Lecocq",
    "Szilard Koszticsak" -> "Szilárd Koszticsák",
    "Tamás Kaszás" -> "Tamás Kaszás",
    "Tamas Kovacs" -> "Tamás Kovács",
    "Tolga Bozoglu" -> "Tolga Bozoğlu",
    "Tytus Zmijewski" -> "Tytus Żmijewski",
    "Umit Bektas" -> "Ümit Bektaş",
    "Vadim Ghirda" -> "Vadim Ghirdă",
    "Valerie Gache" -> "Valérie Gache",
    "Valerie Macon" -> "Valérie Macon",
    "Valery Hache" -> "Valéry Hache",
    "Venturelli" -> "Daniele Venturelli",
    "Vit Simanek" -> "Vít Šimánek",
    "Vladimir Simicek" -> "Vladimír Šimíček",
    "Wiktor Dabkowski" -> "Wiktor Dąbkowski",
    "Wojciech Kruczynski" -> "Wojciech Kruczyński",
    "Wojtek Radwanski" -> "Wojtek Radwański",
    "Yasin Akgul" -> "Yasin Akgül",
    "Yuri Cortez" -> "Yuri Cortéz",
    "Zoltan Gergely Kelemen" -> "Zoltán Gergely Kelemen",
    "Zvonimir Barisin" -> "Zvonimir Barišin"
  )

  override def clean(metadata: ImageMetadata): ImageMetadata = {
    metadata.copy(byline = metadata.byline.flatMap(names.get(_).orElse(metadata.byline)))
  }
}
