cask "AdoptOpenJDK/openjdk/adoptopenjdk8"
cask "guardian/devtools/gu-scala"
brew "guardian/devtools/dev-nginx"
cask "docker"
brew "awscli"
brew "node"

brew "libgd"
brew "graphicsmagick"
brew "imagemagick"
brew "pngquant"
brew "exiftool"

brew "jq"
brew "md5sha1sum"
