#!/bin/bash

export JDK_HOME=/usr/lib/jvm/java-1.7.0

/usr/lib/jvm/java-1.7.0/bin/java \
  -XX:+CMSClassUnloadingEnabled -Xmx2g -XX:MaxPermSize=350m -XX:+UseCompressedOops  \
  -Dbuild.number="$BUILD_NUMBER" -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
  -Dsbt.log.noformat=true -jar sbt-launch.jar "$@" < /dev/null
