package com.gu.mediaservice.lib.guardian

import com.gu.mediaservice.lib.config.{PublicationPhotographers, UsageRightsConfigProvider}

object GuardianUsageRightsConfig extends UsageRightsConfigProvider {
  private val ObserverPublication = "The Observer"
  private val GuardianPublication = "The Guardian"

  val externalStaffPhotographers: List[PublicationPhotographers] = List(
    PublicationPhotographers(GuardianPublication, List(
      "Ben Doherty",
      "Bill Code",
      "Calla Wahlquist",
      "David Sillitoe",
      "Graham Turner",
      "Helen Davidson",
      "Jill Mead",
      //"Jonny Weeks", (Commented out as Jonny's photo's aren't always as Staff.)
      "Joshua Robertson",
      "Rachel Vere",
      "Roger Tooth",
      "Sean Smith",
      "Melissa Davey",
      "Michael Safi",
      "Michael Slezak",
      "Sean Smith",
      "Carly Earl",
      // Past
      "Dan Chung",
      "Denis Thorpe",
      "Don McPhee",
      "Frank Baron",
      "Frank Martin",
      "Garry Weaser",
      "Graham Finlayson",
      "Martin Argles",
      "Peter Johns",
      "Robert Smithies",
      "Tom Stuttard",
      "Tricia De Courcy Ling",
      "Walter Doughty",
      "Eric Wadsworth",
    )),
    PublicationPhotographers(ObserverPublication, List(
      "David Newell Smith",
      "Tony McGrath",
      "Catherine Shaw",
      "John Reardon",
      "Sean Gibson"
    ))
  )

  // these are people who aren't photographers by trade, but have taken photographs for us.
  // This is mainly used so when we ingest photos from Picdar, we make sure we categorise
  // them correctly.
  // TODO: Think about removin these once Picdar is dead.
  val internalStaffPhotographers = List(
    PublicationPhotographers(GuardianPublication, List(
      "E Hamilton West",
      "Harriet St Johnston",
      "Lorna Roach",
      "Rachel Vere",
      "Ken Saunders"
    ))
  )

  val contractedPhotographers = List(
    PublicationPhotographers(ObserverPublication, List(
      "Andy Hall",
      "Antonio Olmos",
      "Gary Calton",
      "Jane Bown",
      "Jonathan Lovekin",
      "Karen Robinson",
      "Katherine Anne Rose",
      "Richard Saker",
      "Sophia Evans",
      "Suki Dhanda"
    )),
     PublicationPhotographers(GuardianPublication, List(
      "Alicia Canter",
      "Antonio Olmos",
      "Christopher Thomond",
      "David Levene",
      "Eamonn McCabe",
      "Graeme Robertson",
      "Johanna Parkin",
      "Linda Nylind",
      "Louise Hagger",
      "Martin Godwin",
      "Mike Bowers",
      "Murdo MacLeod",
      "Sarah Lee",
      "Tom Jenkins",
      "Tristram Kenton",
      "Jill Mead",
    ))
 )

  val staffIllustrators = List(
    "Guardian Design"
  )

  val contractIllustrators = List(
    PublicationPhotographers(GuardianPublication, List(
      "Ben Lamb",
      "Andrzej Krauze",
      "David Squires",
      "First Dog on the Moon",
      "Harry Venning",
      "Martin Rowson",
      "Matt Kenyon",
      "Matthew Blease",
      "Nicola Jennings",
      "Rosalind Asquith",
      "Steve Bell",
      "Steven Appleby",
      "Ben Jennings",
    )),
    PublicationPhotographers(ObserverPublication, List(
      "Chris Riddell",
      "David Foldvari",
      "David Simonds",
    ))
  )

  val creativeCommonsLicense = List(
    "CC BY-4.0", "CC BY-SA-4.0", "CC BY-ND-4.0"
  )

  /* These are currently hardcoded */
  val payGettySourceList = List(
    "ABC News",
    "ABC Studios",
    "Addictive Stock",
    "Aerial Filmworks",
    "AFPTV",
    "Alinari",
    "Anadolu Agency Video",
    "Archive Films: Creative",
    "Archive Films: Editorial",
    "Arnold Newman Collection",
    "Artbeats",
    "Austrian Broadcasting Corporation (ORF)",
    "Baim Collection",
    "Barrett-Jackson",
    "BBC Broadcast Archive",
    "BBC Creative",
    "BBC Editorial",
    "Bloomberg Video",
    "Bob Thomas Sports Photography",
    "Catwalking",
    "Cavan",
    "CBS Creative Video",
    "CBS Media Group",
    "CBS Television Stations Group",
    "CCTV+",
    "Contour",
    "Contour RA",
    "Corbis Creative Video",
    "Corbis Premium Historical",
    "Creatas Video",
    "Creatas Video+",
    "Denver Post",
    "Digital Vision Footage",
    "Discovery Access",
    "Editorial Specials",
    "EFE",
    "FATV",
    "FCCE Films and Stars",
    "FedNet",
    "First Freedom",
    "Fusion",
    "Gamma-Legends",
    "GC Video",
    "Genuine Japan Creative Film",
    "Genuine Japan Editorial Film",
    "Getty Images Editorial Footage",
    "Getty Images Entertainment Video",
    "Getty Images Multimedia",
    "Getty Images Sport Classic",
    "Getty Images Sport Video",
    "Getty Images UGC Video",
    "Getty Images VR",
    "Getty Images VR Editorial",
    "Globo",
    "Hearst Newsreel",
    "Icon Sport",
    "Iconic Images",
    "Iconica Video",
    "Iconica Video: Signature",
    "Image Bank Film",
    "Image Bank Film: Signature",
    "Insight TV",
    "Insight TV Editorial",
    "ITN",
    "ITN Archive",
    "J.LEAGUE",
    "Jupiterfootage",
    "KBC - Japan",
    "Klaud9",
    "Kyodo News",
    "Lichfield Archive",
    "Lighthouse Films",
    "LightRocket Footage",
    "Lonely Planet RF",
    "Major League Baseball Platinum",
    "MediaNews Group",
    "MediaStorm",
    "MediaStorm Editorial",
    "MOFILM",
    "Moment Video Editorial",
    "Moment Video RF",
    "Moment Video RR",
    "Mondadori Portfolio Premium",
    "MTV B-Roll",
    "NBA Classic",
    "NBC News Archives Clips",
    "NBC News Archives Offline",
    "Neil Leifer Collection",
    "Newsday",
    "Newspix",
    "Nexstar",
    "NHK Video Bank Creative",
    "NHK Video Bank Editorial",
    "NHK Video Bank Premium",
    "Nimia",
    "Nimia Signature",
    "Northern Pictures",
    "Nuala Video",
    "NurPhoto Footage",
    "Olympusat",
    "one80",
    "One80: Signature",
    "Oxford Scientific Video",
    "PA Images",
    "PA Media",
    "Papixs",
    "Paramount Pictures",
    "Paris Match Archive",
    "Pele 10",
    "Photodisc",
    "Photolibrary Video",
    "Popperfoto",
    "Premiere Archival Collection",
    "Premium Archive",
    "Premium Archive Films: Editorial",
    "Red Bull Editorial",
    "Reportage Archive",
    "Rumble",
    "SAMURAI JAPAN",
    "Scripps",
    "Seven West Media",
    "Sherman Grinberg Library",
    "Sky News",
    "Sky News Arabia",
    "Smithsonian",
    "SNS Group",
    "Sony Pictures Entertainment",
    "Sports Illustrated",
    "Sports Illustrated Classic",
    "Sportsfile",
    "Storm Shadow",
    "Storyful",
    "StringersHub",
    "Stringr",
    "Sygma Premium",
    "Television New Zealand",
    "The Asahi Shimbun Premium Archive",
    "The Asahi Shimbun Video",
    "The March of Time",
    "Times Network India",
    "TV Asahi Productions",
    "ullstein bild Premium",
    "Ulrich Baumgarten",
    "Universal Studios",
    "Verve",
    "Verve+",
    "Vetta",
    "Vice Media",
    "Vice Media Editorial",
    "Vice News Premium",
    "Video Music Box Licensing",
    "Vision Media",
    "Walt Disney Studios",
    "Warner Bros. Entertainment",
    "WNET Collection",
    "Women Who Drone",
    "XOS Digital",
    "Yann Arthus-Bertrand",
    // Here goes the list of inactive collections too
    "#girlgaze",
    "2VISTA",
    "360cities.net Editorial",
    "360cities.net RM",
    "3D4Medical Film",
    "3D4Medical.com",
    "3DClinic",
    "40260 RF",
    "A Luna Blue RF",
    "ABSODELS RM",
    "ACP",
    "Action Plus",
    "Aflo Foto Agency RM",
    "AFP Creative",
    "age fotostock RM",
    "Ah2",
    "Alaska Stock Images RF",
    "Alaska Stock Images RR",
    "Alaskan Express RF",
    "All Canada Photos RM",
    "Allsport Concepts",
    "Altrendo",
    "Altrendo RR",
    "amana images RM",
    "America 24-7",
    "Anonymous Content",
    "AP Archive RM",
    "ApexStock",
    "arabianEye RM",
    "Arcaid Images",
    "Arcaid RR",
    "Arcangel Images RR",
    "Archive Films",
    "Archive Photos Creative",
    "Arena Football League",
    "Aridi",
    "Art Images",
    "ArtBox RF Film",
    "Artville",
    "ASAblanca",
    "Asia Images RF",
    "Asia Images RM",
    "Astrakan",
    "Atom Factory",
    "Aurora",
    "Aurora Plus",
    "Author's Image RF",
    "AWL Images RM",
    "Axiom Photographic Agency",
    "Barcroft",
    "Bettmann Creative",
    "bilderlounge RR",
    "Biosphoto RM",
    "Black Box",
    "Blend Images RM",
    "Blend Images RR",
    "Bloomberg Creative Photos RM",
    "Bloomberg Premium RR",
    "BLOOMimage RF Film",
    "Bondstreet Images RF",
    "Boost",
    "Botanica",
    "Broadway.com RM",
    "Budget RF Footage",
    "Built.Images RF",
    "Caiafilm",
    "Caiaimage",
    "Canopy RM",
    "Car Culture",
    "Cavan Images RM",
    "CBS Creative Video RR",
    "CBS Media Group RF",
    "CBS Watch Magazine",
    "CBS Watch Magazine Video",
    "CCN Images RR",
    "CF Getty Images Editorial Footage",
    "CF WireImage Video",
    "CGIBackgrounds",
    "Check Six",
    "Chic Sketch Editorial",
    "Chic Sketch RF",
    "China Span RM",
    "Christian Science Monitor",
    "CI BuzzFoto",
    "CI Europa Press",
    "CI FilmMagic",
    "CI FilmMagic, Inc",
    "CI FM Europa Press",
    "CI Getty Images Entertainment",
    "CI Getty Images Sport",
    "CI News Feature",
    "CI WI Europa Press",
    "CI WireImage",
    "Citizen Stock RM",
    "Clerkenwell",
    "clipart.com",
    "Code Red",
    "Codex",
    "Collection Mix Subjects RM",
    "Collection Vogue Paris",
    "Collegiate Images",
    "Colorsport",
    "Comstock Images",
    "Conde Nast Collection Editorial",
    "Conde Nast Collection RM",
    "Conde Nast Lifestyle Collection",
    "Conde Nast Video RF",
    "Conde Nast Video RR",
    "Construction Photography RF",
    "Contour Style",
    "Contour Style Creative",
    "Corbis Documentary",
    "Corbis Editorial Video",
    "Corbis Entertainment Video",
    "Corbis Historical Creative",
    "Corbis NX",
    "Corbis RF",
    "Corbis RM Stills",
    "Cote",
    "CrowdSpark",
    "CSA Images RM",
    "Cuboimages RM",
    "Cultura Exclusive",
    "Cultura RF",
    "Cultura RM",
    "Cusp RM",
    "Custom Medical Stock Photo RF",
    "Custom Medical Stock Photo RM",
    "Cut and Deal RF",
    "Da Vinci Codex Atlanticus",
    "Daily Express",
    "DAJ",
    "DAJ RM",
    "Dave Benett Library",
    "De Agostini RM",
    "Denkou RF",
    "Dick Clark Productions RM",
    "Digital Vision Plus",
    "Discovery Channel Images RM",
    "Disney ABC TV Group Video",
    "DJI",
    "DK Stock",
    "Dorling Kindersley",
    "Eastphoto RF",
    "Eastphoto RM",
    "Ecoscene RR",
    "El Universal",
    "Elias",
    "Emotive Images RF",
    "ESTADÃO CONTEÚDO",
    "Everyday Projects",
    "Eye Ubiquitous RR",
    "EyeEm RM",
    "Eyewire",
    "Eyewire Motion",
    "EyeWire Other",
    "F1online RM",
    "Fame Flynet Stills",
    "Fame Flynet Video",
    "Fancy RF",
    "Federugby",
    "Fever Images RF",
    "Feyenoord",
    "FilmDisc",
    "Finanzen Verlag",
    "First Light",
    "FlashFilm.com RF",
    "Flickr Flash",
    "Flickr Prime",
    "Flickr RR",
    "Flickr State",
    "Flirt RF",
    "FM Europa Press",
    "FogStock",
    "Folio Images RM",
    "FoodCollection Footage",
    "FoodPix",
    "FoodShapes RF",
    "Foto Spring",
    "Fototrove",
    "Fox Entertainment Group",
    "Gallo Images",
    "Gamma-Features",
    "GAP Photos RM",
    "Garden Picture Library RM",
    "Genuine Japan Creative Film",
    "Genuine Japan Creative Stills",
    "Genuine Japan Editorial Film",
    "Genuine Japan Editorial Stills",
    "George Steinmetz",
    "Getty Images - NASCAR Partners",
    "Getty Images Multimedia",
    "Getty Images Special Access",
    "GIEV",
    "Global Cricket Ventures - BCCI",
    "Globo",
    "Glow RM",
    "Glowimages RM",
    "GoGo Images RF",
    "GoodSalt RR",
    "GraphEast RF",
    "GraphEast RM",
    "Guest List",
    "Gulf Images RM",
    "Hemera",
    "Hemis.fr RM",
    "Her Og Nu",
    "Hero Images",
    "Hero Images Corbis",
    "HillCreek Pictures RF",
    "Historic Map Works",
    "Hoberman Collection UK RR",
    "Hola Images RM",
    "Hoxton",
    "Hulton Archive",
    "I Love Images RF",
    "Iconica",
    "Iconotec RF",
    "Ikon Images",
    "Illustration Works",
    "Image Farm RF",
    "Image Ideas RF",
    "Image Partner Media",
    "Image100",
    "imageBROKER RM",
    "ImageDJ RF",
    "Imagemore",
    "ImageRite RF",
    "Images Bazaar",
    "Images.com RF",
    "imageshop RF",
    "imagesouk",
    "ImageState RF",
    "ImageState RM",
    "Imagezoo RM",
    "ImaZinS RM",
    "Indaba Music",
    "Index Stock Images RR",
    "Indian Premier League",
    "Inmagineasia",
    "InsideOutPix RF",
    "Inspirestock RF",
    "Interact Images",
    "International Speedway Corp.",
    "Ioda Music",
    "Iromaya RF",
    "IS Stock RF",
    "iStock Exclusive RF",
    "iStock Main",
    "iStock Signature",
    "iStock Signature Plus",
    "iStock Vectors Plus",
    "ItaliaStock",
    "Jamendo",
    "Jane Goodall Institute",
    "JLPGA",
    "John Warburton-Lee RR",
    "Johner Images",
    "Johner RF Film",
    "Jon Arnold Images RF",
    "JTB Photo RM",
    "Juice Images RF",
    "Jukin Media",
    "Juniors Bildarchiv RM",
    "Kablonk RF",
    "Kallista Images",
    "Keith Levit Photography RF",
    "Keystone RF",
    "Kobal Collection",
    "LA Times RR",
    "Las Vegas Stock RR",
    "LAT",
    "LatinContent Footage RR",
    "LatinContent RM",
    "Laughing Stock RM",
    "Lifesize",
    "Link Image RM",
    "London Stills RR",
    "Lonely Planet Images",
    "LOOK",
    "LuckyPix RR",
    "Luxy",
    "Map Resources",
    "Mary Evans Picture Library RM",
    "Masterfile",
    "Masters",
    "mauritius images RM",
    "Mayo Clinic Collection",
    "MediaStorm Creative",
    "MedioImages",
    "Melba Photo Agency RF",
    "Mike King",
    "Minden Pictures II",
    "Minden Pictures RM",
    "Mint Images RM",
    "Mise En Beaute RR",
    "MLBPA - The Players Choice",
    "Moment RM",
    "Moment Select",
    "Moment Unreleased",
    "Mondadori Portfolio",
    "Music Labels",
    "Muuse Me Latin",
    "National Geographic",
    "National Geographic Creative",
    "National Geographic Creative Video",
    "National Geographic Magazines",
    "National Geographic RF",
    "National Geographic RF Video",
    "Nativestock",
    "Nature Picture Library",
    "Neovision RM",
    "Nettavisen",
    "New York Cosmos",
    "Newsday RR",
    "newstockimages RF",
    "NFL",
    "Nordic Life",
    "Nordic Photos",
    "NucleusMedicalArt.com RM",
    "NYonAir",
    "Oceans-Image RR",
    "Offside Live",
    "OJO Images RM",
    "OJO Plus RF",
    "Old Visuals RF",
    "Olive Images RF",
    "OmniReelLife",
    "Open Door Images RF",
    "Open Mike Productions",
    "Oxford Scientific RM",
    "Pacific Stock RM",
    "PANAPRESS",
    "PanoramaStock RF",
    "Panoramic Images RM",
    "Panoramic Images RR",
    "Panther Media RF",
    "Paris Match Collection",
    "Passage RM",
    "Perspectives",
    "Peter Arnold",
    "Photo Exchange Bank Germany",
    "PhotoAlto Agency RM",
    "Photodisc",
    "Photographer's Choice",
    "Photographer's Choice RR",
    "Photolibrary RF",
    "Photolibrary RM",
    "Photonica",
    "Photonica World",
    "Photononstop RM",
    "Phototake RM",
    "Phovoir RF",
    "Picture Press RM",
    "Pixmann RF",
    "Pixta",
    "Popperfoto Creative",
    "Popstar Pictures",
    "Portsmouth FC",
    "Position Music",
    "Post Holes RF",
    "Premium Ent",
    "Private Label",
    "Publisher Mix RM",
    "Pump Audio",
    "Pump Audio Exclusive",
    "Pump Express",
    "Queerstock",
    "QuickImage RF",
    "QuickImage RR",
    "Radius Images RF",
    "Rainer Schlegelmilch",
    "Real Latino RF",
    "Realistic Reflections",
    "Red Bull Media House Select",
    "Red Cover RM",
    "Redhot Footage",
    "Redlink RM",
    "Reelhouse",
    "Refinery29 RM",
    "relaximages",
    "Reportage by Getty Images",
    "Retrofile",
    "Reunion Images",
    "Riser",
    "Robert Harding World Imagery",
    "Rocketclips",
    "RooM RM",
    "SAKIstyle RM",
    "SambaPhoto",
    "Science Faction",
    "Science Faction Jewels",
    "Science Photo Library RM",
    "Science Source",
    "ScienceFoto RM",
    "Scoopt",
    "Sebun",
    "Silver Bullets",
    "simple stock shots RF",
    "Sites & Photos",
    "Smart.MAGNA RF",
    "Snapwi.re",
    "SodaStyle",
    "SoFood Collection RF",
    "Solus",
    "Somos RF",
    "Sony BMG Music Entertainment",
    "Sony Music",
    "Sound Effects by Getty Images",
    "Soundcloud",
    "SoundExpress",
    "SPL Creative RM",
    "SplashdownDirect.com RF",
    "Sport Plus",
    "Starface Image Collection",
    "Stock Footage World RF",
    "Stock Illustration RF",
    "Stock Illustration Source",
    "Stock4B",
    "stockbrokerXtra RF",
    "Stockbyte",
    "Stockbyte Global",
    "stockbyway RF",
    "Stockdisc",
    "StockFood Creative RM",
    "StockFood Creative RR",
    "StockImage",
    "Stone",
    "Studio Harcourt",
    "SuperStock RF",
    "SuperStock RM",
    "Swimwear by Popstar",
    "Tandem Stock",
    "Tango Stock RM",
    "TAO Images RM",
    "TASS Footage",
    "Taxi",
    "Taxi Japan RM",
    "Televisa",
    "Terry O'Neill",
    "the Agency Collection",
    "The Axel Springer Collection",
    "The England Collection",
    "The Gruner & Jahr Collection",
    "The Image Bank",
    "The LIFE Images Collection",
    "The LIFE Picture Collection",
    "The LIFE Premium Collection",
    "The New York Post",
    "The Stock Connection RR",
    "The StockPile Collection RF",
    "Thinkstock",
    "TIBFilm",
    "TIBFilm Signature",
    "Tim de Waele",
    "Tohoku Colour Agency RM",
    "TongRo Images RF",
    "Topic Images",
    "Travels to the Edge RR",
    "Triangle",
    "Tribe of Noise",
    "Tribune",
    "Trond Tandberg",
    "Twenty20 RF",
    "Universal Images Group",
    "Untitled X-Ray",
    "Uppercut RM",
    "Urban CGI RF",
    "Value RF Footage",
    "Vice News Premium",
    "Videofashion News Library",
    "View Stock RM",
    "VII",
    "VII Premium",
    "VisitBritain RF",
    "VisitBritain RM",
    "Visual China Group Video",
    "Visual Language RF",
    "Visuals Unlimited",
    "Warner Bros. Entertainment",
    "WaterFrame RM",
    "Wembley National Stadium Ltd",
    "West Ham United FC",
    "Westend61 RM",
    "Wholly-Owned Royalty-Free Music",
    "WI Europa Press",
    "WIN-Initiative RM",
    "Wooshii",
    "Workbook Stock",
    "World Kabbadi League",
    "World Sport Group",
    "X-Treme Video",
    "Yann Arthus-Bertrand",
    "Zefa RF",
    "Zen Shui RF"
  )

  val freeSuppliers = List(
    "AAP",
    "Alamy",
    "Allstar Picture Library",
    "AP",
    "EPA",
    "Getty Images",
    "PA",
    "Reuters",
    "Rex Features",
    "Ronald Grant Archive",
    "Action Images",
    "Action Images/Reuters"
  )

  val suppliersCollectionExcl = Map(
    "Getty Images" -> payGettySourceList
  )

}
