AWSTemplateFormatVersion: '2010-09-09'
Description: Media Service Dev

Parameters:
  # These buckets are required to get Guardian-specific quotas and usage data
  CreateUsageAndQuotaBuckets:
    Type: String
    AllowedValues: [true, false]
    Default: false

Conditions:
  CreateUsageAndQuotaBuckets:
    !Equals [!Ref CreateUsageAndQuotaBuckets, true]

Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedMethods:
          - GET
          AllowedOrigins:
          - '*'
          ExposedHeaders:
          - Date
          MaxAge: '3600'

  ThumbBucket:
    Type: AWS::S3::Bucket

  KeyBucket:
    Type: AWS::S3::Bucket

  ImageOriginBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  ConfigBucket:
    Type: AWS::S3::Bucket
    Condition: CreateUsageAndQuotaBuckets

  S3WatcherIngestBucket:
    Type: AWS::S3::Bucket

  S3WatcherFailBucket:
    Type: AWS::S3::Bucket

  CollectionsBucket:
    Type: AWS::S3::Bucket

  UsageMailBucket:
    Type: AWS::S3::Bucket
    Condition: CreateUsageAndQuotaBuckets
    Properties:
      VersioningConfiguration:
        Status: Enabled

  EditsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  CollectionsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  ImageCollectionsDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  LeasesDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: mediaId
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      GlobalSecondaryIndexes:
      - IndexName: mediaId
        KeySchema:
        - AttributeName: mediaId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'

  ThrallMessageQueue:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: media-service-thrall-DEV
      ShardCount: 1
      RetentionPeriodHours: 168
      Tags:
      - { Key: Stack, Value: media-service }
      - { Key: Stage, Value: DEV }

  # TODO MRB: remove this when we migrate to Kinesis
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !GetAtt 'Queue.Arn'
        Protocol: sqs
  Queue:
    Type: AWS::SQS::Queue
    Properties: {}
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: MyQueuePolicy
        Statement:
        - Sid: Allow-SendMessage-To-Queue-From-Topic
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - sqs:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref 'Topic'
      Queues:
      - !Ref 'Queue'
  IndexedImageTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !GetAtt 'IndexedImageMetadataQueue.Arn'
        Protocol: sqs
  IndexedImageMetadataQueue:
    Type: AWS::SQS::Queue
    Properties: {}
  IndexedImageMetadataQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: IndexedImageMetadataQueuePolicy
        Statement:
        - Sid: Allow-SendMessage-To-Queue-From-Topic
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - sqs:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref 'IndexedImageTopic'
      Queues:
      - !Ref 'IndexedImageMetadataQueue'

  UsageRecordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: usage_id
        AttributeType: S
      - AttributeName: grouping
        AttributeType: S
      - AttributeName: media_id
        AttributeType: S
      KeySchema:
      - AttributeName: grouping
        KeyType: HASH
      - AttributeName: usage_id
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: media_id
        KeySchema:
        - AttributeName: media_id
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: '1'
          WriteCapacityUnits: '1'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  LiveContentPollTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  PreviewContentPollTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

Outputs:
  ImageBucket:
    Value: !Ref 'ImageBucket'
  ThumbBucket:
    Value: !Ref 'ThumbBucket'
  KeyBucket:
    Value: !Ref 'KeyBucket'
  ImageOriginBucket:
    Value: !Ref 'ImageOriginBucket'
  ImageOriginWebsite:
    Value: !GetAtt 'ImageOriginBucket.WebsiteURL'
  ConfigBucket:
    Value: !If [CreateUsageAndQuotaBuckets, !Ref 'ConfigBucket', "null"]
  CollectionsBucket:
    Value: !Ref 'CollectionsBucket'
  S3WatcherIngestBucket:
    Value: !Ref 'S3WatcherIngestBucket'
  S3WatcherFailBucket:
    Value: !Ref 'S3WatcherFailBucket'
  UsageMailBucket:
    Value: !If [CreateUsageAndQuotaBuckets, !Ref 'UsageMailBucket', "null"]
  EditsDynamoTable:
    Value: !Ref 'EditsDynamoTable'
  CollectionsDynamoTable:
    Value: !Ref 'CollectionsDynamoTable'
  ImageCollectionsDynamoTable:
    Value: !Ref 'ImageCollectionsDynamoTable'
  LeasesDynamoTable:
    Value: !Ref 'LeasesDynamoTable'
  SnsTopicArn:
    Value: !Ref 'Topic'
  SqsQueueUrl:
    Value: !Ref 'Queue'
  IndexedImageTopicArn:
    Value: !Ref 'IndexedImageTopic'
  IndexedImageMetadataQueueUrl:
    Value: !Ref 'IndexedImageMetadataQueue'
  UsageRecordTable:
    Value: !Ref 'UsageRecordTable'
  LiveContentPollTable:
    Value: !Ref 'LiveContentPollTable'
  PreviewContentPollTable:
    Value: !Ref 'PreviewContentPollTable'
  ThrallMessageQueue:
    Value: !Ref 'ThrallMessageQueue'
  QuotaStoreKey:
    Value: !If [CreateUsageAndQuotaBuckets, "rcs-quota.json", "null"]
