FROM java:openjdk-8-jdk

RUN apt-get --yes update && apt-get --yes install \
  apt-transport-https

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

RUN apt-get --yes update && apt-get --yes install \
  sbt

COPY entrypoint.sh /
