# NB: Although graphicsmagick is only explicitly required by image-loader and cropper,
# we install them in this image for the advantage having a single file to manage.

FROM java:8
MAINTAINER The Guardian

RUN apt-get --yes update && apt-get --yes install apt-transport-https

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823

RUN apt-get --yes update && apt-get --yes install \
  sbt \
  graphicsmagick \
  graphicsmagick-imagemagick-compat
