FROM elasticsearch:1.7.1
MAINTAINER The Guardian

RUN /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head
RUN /usr/share/elasticsearch/bin/plugin -install karmi/elasticsearch-paramedic
