rootLogger: INFO, file

logger:
  # log action execution errors for easier debugging
  action: DEBUG

  # aws
  com.amazonaws: WARN

  # gateway
  gateway: DEBUG
  index.gateway: DEBUG

  # peer shard recovery
  indices.recovery: DEBUG

  # discovery
  discovery: DEBUG

  index.search.slowlog: TRACE, index_search_slow_log_file
  index.indexing.slowlog: TRACE, index_indexing_slow_log_file

additivity:
  index.search.slowlog: false
  index.indexing.slowlog: false

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "%d{ISO8601} %-5p %-25c %m%n"

  file:
    type: file
    file: ${path.logs}/elasticsearch.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "%d{ISO8601} %-5p %-25c %m%n"

  index_search_slow_log_file:
    type: file
    file: ${path.logs}/elasticsearch-index-search-slowlog.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "%d{ISO8601} %-5p %-25c %m%n"

  index_indexing_slow_log_file:
    type: file
    file: ${path.logs}/elasticsearch-index-indexing-slowlog.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "%d{ISO8601} %-5p %-25c %m%n"
