load_module /usr/lib/nginx/modules/ngx_http_image_filter_module.so;
events {
  worker_connections  1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  sendfile           on;
  keepalive_timeout  65;

  # Chain of maps to strip the q,w,h,r params from image proxy requests, as they'll confuse the
  # signature verification if they're included in the request to AWS.
  # This chain needs to be built here instead of in the location block due to nginx limitations.
  map $args  $no_q { "~*^(.*)(?:(?:^|&)q=[^&]*)(.*)$" $1$2; default $args; }
  map $no_q  $no_w { "~*^(.*)(?:(?:^|&)w=[^&]*)(.*)$" $1$2; default $no_q; }
  map $no_w  $no_h { "~*^(.*)(?:(?:^|&)h=[^&]*)(.*)$" $1$2; default $no_w; }
  map $no_h  $no_r { "~*^(.*)(?:(?:^|&)r=[^&]*)(.*)$" $1$2; default $no_h; }
  # Then another pass to remove any leading, trailing or doubled '&'s
  map $no_r $clean_leading { "~^&+(.*)" $1; default $no_r; }
  map $clean_leading $clean_trailing { "~(.*)&+$" $1; default $clean_leading; }
  map $clean_trailing $final_clean_args { "~(?<pre>.*)&&+(?<post>.*)" "$pre&$post"; default $clean_trailing; }

  # $final_clean_args is now ready to be included in the proxy requests.

  server {
    listen 80;

    charset utf-8;
    proxy_intercept_errors on;

    # This is our healthcheck
    location /_ {
      return 200 'OK';
      add_header Content-Type text/plain;
    }

    location / {
      # docker dns resolver
      resolver 127.0.0.11;

      # We might need to review what we do with bigger images
      image_filter_buffer 50M;
      image_filter_interlace on;
      image_filter_jpeg_quality $arg_q;
      image_filter resize $arg_w $arg_h;
      image_filter rotate $arg_r;

      # connect to the localstack docker container
      proxy_pass http://localstack:4566$uri?final_clean_args;
    }
  }
}
